# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JetRubyTest' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for JetRubyTest
    
    pod 'Alamofire', '~> 4.5'
    pod 'Argo', '~> 4.0'
    pod 'Curry'
    
    target 'JetRubyTestTests' do
        inherit! :search_paths
        pod 'Argo', '~> 4.0'
        pod 'Curry'
    end
    
end


